TCID-28 3.0 Send a Waitlist Offer Magic Button
lumahealthhq/automated-tests pull request #26
Opened 2022-02-03 10:21 UTC by Dziana-Bychkova

[TCID-28 allure.zip](https://github.com/lumahealthhq/automated-tests/files/7993618/TCID-28.allure.zip)

2022-02-03 18:55 UTC, NatalliaSamarava requested changes

2022-02-03 18:55 UTC, NatalliaSamarava commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +Given I am on a page with the URL '${mainPageUrl}${oppidVariable}'
Why we can't use ${web-application.main-page-url}

2022-02-03 18:55 UTC, NatalliaSamarava commented on src/main/resources/properties/environment/demo/environment.properties
> +bdd.variables.global.mainPageUrl=https://app.lumahealthdemo.com/demo-setup?oppid=
No need to add this parameter.

2022-02-03 18:55 UTC, NatalliaSamarava commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +When I open URL `${baseApiUrl}/demoUsers/${oppidVariable}/messages/patientApptOffer` in new window
Use composite step ```When I use magic button `$magicButtonName` for the current patient```

2022-02-03 18:55 UTC, NatalliaSamarava commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +When I change context to element located `xpath(//*[contains(text(),'Thanks.')])`
We can use step ```Then number of elements found by `xpath(//*[text()="Thanks. We're checking with the front office and will send you another message when confirmed.")])` is equal to `1` ```

2022-02-03 18:55 UTC, NatalliaSamarava commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +Then JSON element by JSON path `$..text` is equal to `["${offerMessage}"]`IGNORING_ARRAY_ORDER,IGNORING_EXTRA_ARRAY_ITEMS
replace parameter with a text string

2022-02-04 06:17 UTC, Dziana-Bychkova commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +Given I am on a page with the URL '${mainPageUrl}${oppidVariable}'
For  forming different users, we should use a different oppid, if you use ${web-application.main-page-url}, then the same user is used, manual testers explained to me that this is not very correct, so I use this url with a new oppid.

2022-02-04 06:19 UTC, Dziana-Bychkova commented on src/main/resources/properties/environment/demo/environment.properties
> +bdd.variables.global.mainPageUrl=https://app.lumahealthdemo.com/demo-setup?oppid=
This parameter is needed to form a new user in the test scenario.

2022-02-04 06:21 UTC, Dziana-Bychkova commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +When I open URL `${baseApiUrl}/demoUsers/${oppidVariable}/messages/patientApptOffer` in new window
I don't use this composite step, because the step in it Then `${magicButtonMessage}` matches `Thanks you! Your magic request to send <magicButtonName> to demo patient .* has been processed.` falled, because the mesage differs from the <magicButtonName>.

2022-02-04 06:24 UTC, Dziana-Bychkova commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +Then JSON element by JSON path `$..text` is equal to `["${offerMessage}"]`IGNORING_ARRAY_ORDER,IGNORING_EXTRA_ARRAY_ITEMS
Done.

2022-02-04 06:32 UTC, Dziana-Bychkova commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +When I change context to element located `xpath(//*[contains(text(),'Thanks.')])`
Done.

2022-02-04 08:21 UTC, NatalliaSamarava requested changes

2022-02-04 08:21 UTC, NatalliaSamarava commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +Given I am on a page with the URL '${mainPageUrl}${oppidVariable}'
Discussed with manual tester, the issues will not occur when running tests one by one. Please use same approach as in other stories.

2022-02-04 08:21 UTC, NatalliaSamarava commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +When I open URL `${baseApiUrl}/demoUsers/${oppidVariable}/messages/patientApptOffer` in new window
Please replace with composite

2022-02-04 08:21 UTC, NatalliaSamarava commented on src/main/resources/properties/environment/demo/environment.properties
> +bdd.variables.global.mainPageUrl=https://app.lumahealthdemo.com/demo-setup?oppid=
Please, remove it, as it will no longer be needed.

2022-02-04 10:36 UTC, Dziana-Bychkova commented on src/main/resources/properties/environment/demo/environment.properties
> +bdd.variables.global.mainPageUrl=https://app.lumahealthdemo.com/demo-setup?oppid=
Done

2022-02-04 10:36 UTC, Dziana-Bychkova commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +When I open URL `${baseApiUrl}/demoUsers/${oppidVariable}/messages/patientApptOffer` in new window
Done

2022-02-04 10:37 UTC, Dziana-Bychkova commented on src/main/resources/story/web/waitlist/SendAwaitlistOfferMagicButton.story
> +Given I am on a page with the URL '${mainPageUrl}${oppidVariable}'
Done

2022-02-04 13:01 UTC, NatalliaSamarava approved these changes

2022-02-04 13:01 UTC, merged