Update TC 24, 31,37 and edit login step
lumahealthhq/automated-tests pull request #33
Opened 2022-02-17 14:13 UTC by oksanapishchykepam

2022-02-17 15:00 UTC, NatalliaSamarava commented on src/main/resources/story/web/reminder/MessageWithLinkToPSAppointmentSchedulerMagicButton.story
> +When I click on element located `xpath(//*[contains(text(), 'Review and book')]/parent::div/div/descendant::*[contains(text(), 'SEND APPOINTMENT REQUEST') or contains(text(), 'Submit Request')])`
Same as above

2022-02-21 12:46 UTC, oksanapishchykepam commented
[allure_MessageWithNoLinkDEMO.zip](https://github.com/lumahealthhq/automated-tests/files/8109233/allure_MessageWithNoLinkDEMO.zip)

2022-02-21 13:16 UTC, oksanapishchykepam commented
[allure_SendWaitingRoom_DEMO.zip](https://github.com/lumahealthhq/automated-tests/files/8109432/allure_SendWaitingRoom_DEMO.zip)

2022-02-21 19:27 UTC, NatalliaSamarava requested changes

2022-02-21 19:27 UTC, NatalliaSamarava commented on src/main/resources/story/web/customActions/SendWaitingRoomTextMagicButton.story
>  When I wait until element located `xpath(//*[contains(text(),'Thanks')])` appears
replace with ```When I wait until element located `xpath(//*[contains(text(),'Thanks for letting us know')])` appears```

2022-02-21 19:27 UTC, NatalliaSamarava commented on src/main/resources/story/web/customActions/SendWaitingRoomTextMagicButton.story
> +When I wait until element located `By.xpath(//div[text()='arrived'])` appears
remove this wait

2022-02-22 08:49 UTC, NatalliaSamarava approved these changes

2022-02-22 09:07 UTC, merged