Update TC26
lumahealthhq/automated-tests pull request #34
Opened 2022-02-21 11:06 UTC by oksanapishchykepam

2022-02-21 12:47 UTC, oksanapishchykepam commented
[allure_ReplyYesIntakeDEMO.zip](https://github.com/lumahealthhq/automated-tests/files/8109255/allure_ReplyYesIntakeDEMO.zip)

2022-02-21 19:38 UTC, NatalliaSamarava requested changes

2022-02-21 19:38 UTC, NatalliaSamarava commented on src/main/resources/story/web/reminder/ReplyYesIntakeFormMagicButton.story
>  Meta:
Move this scenario before (STEP 4). As in this scenario we are waiting for confirmation from LUMA. and in STEP 4 we are checking that status was changed to Confirm.

2022-02-22 08:47 UTC, NatalliaSamarava approved these changes

2022-02-22 08:47 UTC, merged